


end: a	#rule run if a is leater than end
	echo end	#rule for creating end file	

a: b		# run if b is leater than a
	echo a		#rule for creating a file

b: 			# run newer 
	echo b		# rule for creating b file



