


end: a	#regul run if a is leater than end
	echo end	#regul for creating end file	

a: b		# run if b is leater than a
	echo a		#regul for creating a file

b: 			# run newer 
	echo b		# regul for creating b file



